
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog-pro?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    #??SQL??????
    show-sql: true
    #关闭一个警告
    open-in-view: false
logging:
  level:
    root: warn
    com.blogfirsttry: info
  file:
    path: log/blog-pro.log
server:
  port: 8081